include env.mk

INSTALL_DIR ?= $(PWD)/.install

TARGET_NAME = pcre
TARGET_VERSION = 8.44
#2020.81
TARGET_FULL_NAME = $(TARGET_NAME)-$(TARGET_VERSION)
TARGET_ARCH_NAME = $(TARGET_FULL_NAME).tar.gz
TARGET_ARCH = $(DL_DIR)/$(TARGET_ARCH_NAME)
SRC_URI = https://ftp.pcre.org/pub/$(TARGET_NAME)/$(TARGET_ARCH_NAME)

TARGET_DIR = $(BUILD_DIR)/$(TARGET_FULL_NAME)
TARGET_BIN = $(TARGET_DIR)/pcregrep
TARGET = $(INSTALL_DIR)/bin/pcregrep
#BUILD_OPTS = PREFIX=$(INSTALL_DIR) CROSS_COMPILE=$(CROSS_COMPILE) 
#PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp"
#LZO_DIR=$(BUILD_DIR)/lzo-2.10/.install
#OPENSSL_DIR=$(BUILD_DIR)/openssl-1.1.1j/.install


$(TARGET): $(TARGET_DIR) $(TARGET_BIN)
	$(LOCAL_MAKE) -C $(TARGET_DIR) install
#	mkdir -p $(INSTALL_DIR)/etc/dropbear
#	make -C $(TARGET_DIR) $(BUILD_OPTS) install-dropbear

$(TARGET_BIN): $(TARGET_DIR)/Makefile
	$(LOCAL_MAKE) -C $(TARGET_DIR)
    
$(TARGET_DIR)/Makefile:
	cd $(TARGET_DIR) && \
	./configure \
        --target=$(ARM_HOST) \
        --host=$(ARM_HOST) \
        --build=i686-pc-linux-gnu \
        --prefix=$(INSTALL_DIR) 


#    CC=$(CROSS_COMPILE)gcc \
#    CXX=$(CROSS_COMPILE)g++ \


$(TARGET_DIR): $(TARGET_ARCH)
	tar -C $(BUILD_DIR) -xmvf $(TARGET_ARCH)

$(TARGET_ARCH): 
	wget $(SRC_URI) -O $@


